ACHV = [{"name": "Welcome to Hell", "desc": "یه بازی بکن"},
        {"name": "Welcome to the Asylum", "desc": "تو یه بازی با حالت آشوب شرکت کن"},
        {"name": "Alzheimer's Patient", "desc": "یه بازی تو مود فراموشی انجام بده"},
        {"name": "O HAI DER!", "desc": "با سازنده ربات توی یه بازی شرکت کن"},
        {"name": "Spy vs Spy", "desc": "یه بازی تو مود سکرت انجام بده (نقشا مخفی باشن)"},
        {"name": "Explorer", "desc": "تو ۱۰تا گروه مختلف حداقل دوتا بازی بکن", "inactive":True},
        {"name": "Linguist", "desc": "توی مودهای مربوط به ۱۰ زبان مختلف هر زبان حداقل ۲تا بازی داشته باش", "inactive":True},
        {"name": "I Have No Idea What I'm Doing", "desc": "یه بازی تو مود فراموشی که نقش‌ها هم مخفی باشه (مود سکرت) انجام بده"},
        {"name": "Enochlophobia", "desc": "تو یه بازی که ۳۵ نفر بازیکن داره شرکت کنی"},
        {"name": "Introvert", "desc": "تو یه بازی که کلا ۵ نفر بازیکن داره شرکت کنی"},
        {"name": "Naughty!", "desc": "یه مود بی ادبی بازی کنی"},
        {"name": "Dedicated", "desc": "۱۰۰ تا بازی بکن"},
        {"name": "Obsessed", "desc": "تعداد بازیات برسه به  ۱۰۰۰"},
        {"name": "Here's Johnny!", "desc": "قاتل باشی و ۵۰ نفر رو بکشی (کلا)", "not_via_playing":True},
        {"name": "I've Got Your Back", "desc": "فرشته باشی و جون ۵۰ نفر رو نجات بدی (کلا)", "not_via_playing":True},
        {"name": "Masochist", "desc": "منافق شو و بازی رو ببر"},
        {"name": "Wobble Wobble", "desc": "تو یه بازی که حداقل ۱۰ نفر بازیکن داشته باشه نقش مست رو بگیر و تا آخر بازی زنده بمون"},
        {"name": "Inconspicuous", "desc": "توی یه بازی که حداقل ۲۰تا بازیکن داشته باشه حتی یه نفر بهت رای نده و تا آخر بازی زنده باشی"},
        {"name": "Survivalist", "desc": "تو ۱۰۰ تا بازی نمیر (تا آخر زنده بمون)"},
        {"name": "Black Sheep", "desc": "تو ۳ بازی پشت سر هم همون روز اول اعدامت کنن", "inactive":True},
        {"name": "Promiscuous", "desc": "فاحشه بشی و توی یک بازی که بیش‌تر از ۵ شب طول بکشه هر شب خونه یه نفر بری و خونه کسی دو بار نری"},
        {"name": "Mason Brother", "desc": "حداقل دوتا فراماسون تا آخر بازی زنده بمونن و تو یکیشون باشی"},
        {"name": "Double Shifter", "desc": "نقشت دو بار تو یه بازی عوض بشه (فرقه شدن حساب نیست)"},
        {"name": "Hey Man, Nice Shot", "desc": "کلانتر بشی و بعد مرگت قاتل یا گرگ رو بکشی"},
        {"name": "That's Why You Don't Stay Home", "desc": "گرگ یا فرقه باشی و فاحشه‌ای که شب خونه مونده باشه رو بخوری یا تبدیلش کنی"},
        {"name": "Double Vision", "desc": "دوتا پیشگو همزمان توی بازی باشن و تو یکیشون باشی"},
        {"name": "Double Kill", "desc": "تو بازی شرکت کنی که آخرش فقط قاتل و کلانتر زنده مونده باشن (که خب تهش هم همدیگه رو میکشن و همه می‌بازن)"},
        {"name": "Should Have Known", "desc": "پیشگو باشی و شاهد (ناظر) رو استعلام کنی"},
        {"name": "I See a Lack of Trust", "desc": "پیشگو باشی و روستا همون روز اول اعدامت کنه"},
        {"name": "Sunday Bloody Sunday", "desc": "تو یه شب ۴ نفر بمیرن و تو جزوشون باشی"},
        {"name": "Change Sides Works", "desc": "نقشت تو بازی عوض بشه و بازی رو ببری"},
        {"name": "Forbidden Love", "desc": "خودت یه روستایی ساده باشی و عشقت گرگ (یا برعکس) و بازی رو ببرین"},
        {"name": "Developer", "desc": "Have a pull request merged into the repo", "not_via_playing":True},
        {"name": "The First Stone", "desc": "تو یه بازی برای ۵ روز اولین نفر رای بده"},
        {"name": "Smart Gunner", "desc": "تفنگدار باشی و با هر دو تیرت قاتل/گرگ/فرقه‌گرا بکشی"},
        {"name": "Streetwise", "desc": "کارآگاه شو و ۴ شب پشت سر هم گرگ/قاتل/فرقه‌گرا پیدا کن"},
        {"name": "Speed Dating", "desc": "الهه عشق کسی رو عاشق نکنه و ربات به جاش دو نفر رو عاشق کنه که یکیشون تو باشی"},
        {"name": "Even a Stopped Clock is Right Twice a Day", "desc": "احمق باشی و تا آخر بازی حداقل دوتا از پیشگویی‌هات درست از آب دربیان"},
        {"name": "So Close!", "desc": "منافق که شدی، روستا تلاش کنه اعدامت کنه ولی مساوی بشه و اعدام نشی"},
        {"name": "Cultist Convention", "desc": "یکی از ۱۰ فرقه‌گرای زنده در آخر بازی باش"},
        {"name": "Self Loving", "desc": "الهه که شدی خودتو عاشق کن"},
        {"name": "Should've Said Something", "desc": "گرگ شو و عشقتو بخور! (شب اول حساب نیست)"},
        {"name": "Tanner Overkill", "desc": "منافق بشی و همه بهت رای بدن (به جز خودت)"},
        {"name": "Serial Samaritan", "desc": "قاتل شو و ۳تا گرگ رو بکش"},
        {"name": "Cultist Fodder", "desc": "اون فرقه‌گرای بدبختی باشی که بفرستن بره شکار رو فرقه کنه (و طبیعتا بمیری)"},
        {"name": "Lone Wolf", "desc": "تو یه بازی با حالت آشوب که حداقل ۱۰ نفر بازیکن باشه تک گرگ باشی و بازی رو ببری"},
        {"name": "Pack Hunter", "desc": "۷ تا گرگ زنده تو بازی باشن و تو یکیشون باشی"},
        {"name": "Saved by the Bull(et)", "desc": "توی یه بازی، تعداد گرگ‌های زنده با روستایی‌های زنده برابر باشه، ولی چون تفنگدار هنوز یه گلوله داره بازی تموم نشه، و تو توی تیم روستا باشی"},
        {"name": "In for the Long Haul", "desc": "تو یه بازی حداقل برا ۱ ساعت زنده بمون"},
        {"name": "OH SHI-", "desc": "عشقت رو همون شب اول بکش (فقط برای گرگ و قاتل ممکنه)"},
        {"name": "Veteran", "desc": "۵۰۰ تا بازی بکن"},
        {"name": "No Sorcery!", "desc": "گرگ باشی و جادوگر بخوری!"},
        {"name": "Wuffie-Cult", "desc": "گرگ آلفا باشی و بتونی ۳ نفر رو تبدیل کنی"},
        {"name": "Three Little Wolves and a Big Bad Pig", "desc": "جادوگر بشی و آخر بازی با حداقل ۳تا گرگ همگی زنده بمونین"},
        {"name": "I Helped!", "desc": "توله گرگ باشی و بعد مردنت گرگا بتونن با موفقیت دو نفرو بخورن"},
        {"name": "Cultist Tracker", "desc": "شکارچی باشی و حداقل سه تا فرقه‌گرا رو بکشی"},
        {"name": "I'M NOT DRUN-- *BURPPP*", "desc": "تو یه بازی پسر گیج باشی و سه بار بتونی درست رای بدی"},
        {"name": "Did you guard yourself?", "desc": "تو یه بازی فرشته باشی و ۳ بار بتونی بدون این که گرگ بکشتت ازش محافظت کنی"},
        {"name": "Spoiled Rich Brat", "desc": "اون شاهزاده بدبختی باشی که دو بار اعدامش کنن"},
        {"name": "President", "desc": "کدخدا باشی و بعد مهر زدن بتونی ۳ شب رای بدی"},
        {"name": "It Was a Busy Night!", "desc": "تو یه شب ۳ نفر بیان سراغت"}]
